steps:
  - name: 'ubuntu'
    args: ['env']
    secretEnv: ['EXAMPLE']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/example/versions/1
      env: 'EXAMPLE'
serviceAccount: projects/$PROJECT_ID/serviceAccounts/gcp-cloud-build-demo@simon-karman-cloud-build-demo.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
