steps:
  - name: 'ubuntu'
    args:
    - bash
    - -c
    - |
      pwd
      echo 'inside a file!' > /example/test.txt
    volumes:
      - name: "example"
        path: /example
  - name: 'ubuntu'
    args: ['cat', '/example/test.txt']
    volumes:
      - name: "example"
        path: /example

